name: Generate Stats Images

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: 'x64'

    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/.github/scripts/github-stats/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
        
    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r .github/scripts/github-stats/requirements.txt

    - name: Generate images
      run: |
        cd .github/scripts/github-stats
        python3 generate_images.py
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ankush850

    - name: Commit to the output branch of repo
      run: |
        git config --global user.name "github-stats[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m 'temp commit' || echo
        git checkout output 2>/dev/null || git checkout --orphan output && git rm -rf . && git checkout main -- .github/scripts/github-stats/generated/
        # Move generated files to root
        mv .github/scripts/github-stats/generated/* ./ || echo
        rm -rf .github
        git add .
        git commit -m 'Update generated files' || echo
        git push origin output -f
